title: Belkirk College of Engineering
short_title: Belkirk
description: Jekyll demo for Forestry CMS
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "_posts/en"
      type: posts
    values:
      lang: en
  - scope:
      path: "_posts/fr"
      type: posts
    values:
      lang: fr

collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
