---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: _people
  label: People
  create: all
  match: "*"
  templates:
  - person
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "*"
  templates:
  - project
- type: document
  path: _data/information.yml
  label: Contact Information
upload_dir: ''
public_path: ''
front_matter_path: https://res.cloudinary.com/forestry-demo/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
