---
label: default
hide_body: true
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: description
  label: Description
  description: A short description of the page
  config:
    required: true
    wysiwyg: true
    schema:
      format: html-blocks
- type: datetime
  name: publish_date
  label: Publish Date
  config:
    required: true
- type: text
  name: layout
  label: layout
  hidden: true
  default: post
- name: background_color
  type: color
  label: background_color
  config:
    required: true
    color_format: Hex
  default: "#9B9B9B"
